name: unitierraaca
favicon: null
layout_spectrum: 0.649467563489452
typography_spectrum: 0.92835554596968
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2340934667736292
  lightness: 0.8094572604168206
  saturation: 0.4162090972531587
  rhythmicContrast: 0.285812112968415
purpose: []
