name: unitierraaca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fefefc'
    - '#fdba29'
    - '#dc3923'
    - '#1f6da0'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
