name: unitierraaca
favicon: null
layout_spectrum: 1
typography_spectrum: 0.70836
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#93a5d3'
    - '#553f94'
    - '#edd101'
    - '#0592a1'
  brandStrength: 0.625
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
